//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignement5.NearestStore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/NearestStore")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignement5.NearestStore.Service[] servicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hours {
            get {
                return this.hoursField;
            }
            set {
                if ((object.ReferenceEquals(this.hoursField, value) != true)) {
                    this.hoursField = value;
                    this.RaisePropertyChanged("hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longName {
            get {
                return this.longNameField;
            }
            set {
                if ((object.ReferenceEquals(this.longNameField, value) != true)) {
                    this.longNameField = value;
                    this.RaisePropertyChanged("longName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string region {
            get {
                return this.regionField;
            }
            set {
                if ((object.ReferenceEquals(this.regionField, value) != true)) {
                    this.regionField = value;
                    this.RaisePropertyChanged("region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignement5.NearestStore.Service[] services {
            get {
                return this.servicesField;
            }
            set {
                if ((object.ReferenceEquals(this.servicesField, value) != true)) {
                    this.servicesField = value;
                    this.RaisePropertyChanged("services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/NearestStore")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceNameField, value) != true)) {
                    this.serviceNameField = value;
                    this.RaisePropertyChanged("serviceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NearestStore.INearestStore")]
    public interface INearestStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INearestStore/GetNearestStore", ReplyAction="http://tempuri.org/INearestStore/GetNearestStoreResponse")]
        Assignement5.NearestStore.Store[] GetNearestStore(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INearestStore/GetNearestStore", ReplyAction="http://tempuri.org/INearestStore/GetNearestStoreResponse")]
        System.Threading.Tasks.Task<Assignement5.NearestStore.Store[]> GetNearestStoreAsync(string zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INearestStoreChannel : Assignement5.NearestStore.INearestStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NearestStoreClient : System.ServiceModel.ClientBase<Assignement5.NearestStore.INearestStore>, Assignement5.NearestStore.INearestStore {
        
        public NearestStoreClient() {
        }
        
        public NearestStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NearestStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NearestStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NearestStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Assignement5.NearestStore.Store[] GetNearestStore(string zipcode) {
            return base.Channel.GetNearestStore(zipcode);
        }
        
        public System.Threading.Tasks.Task<Assignement5.NearestStore.Store[]> GetNearestStoreAsync(string zipcode) {
            return base.Channel.GetNearestStoreAsync(zipcode);
        }
    }
}
